### ISSUE TITLE
SourceForge Web領域のバックアップ

### ISSUE THREAD

**Issue by kobake** [sakura-editor/sakura-editor.github.io#12]
時間あるときに。

サイズとファイル数が多くてけっこう時間かかりそうです。

**Comment by kobake** [comment]
https://sakura-editor.osdn.jp/
ここに htmlhelp, htmlhelp2 のバックアップを zip で置いておきました。
ちょっとずつ増やしていきます。

**Comment by kobake** [comment]
> Webサイトにバックアップ置いたんですね。
> ファイルストレージ機能がOnになってたのでてっきりそっちに置いたのばかりおもって、どうやってるんだろうって調べてました^^;

本当はファイルストレージのほうを利用しようと思っていたのですが、何故か認証通らず意味わからなくて Web 領域のほうに繋げてみたら SCP 通ったのでそっちに置いてみた、という経緯です( ´Д`)

参考にしたのはココ。
https://osdn.net/projects/sakura-editor/info/

> このまえ、osdnのprojectのWebページを、
> https://sakura-editor.github.io/
> に設定変えちゃったので、osdnのWebサイトへのリンクが無いんですよね。

そのままで良いと思います。
https://sakura-editor.osdn.jp/ は一般の人はまず見ないところなので。
逆に一般の人に https://sakura-editor.osdn.jp/ に来られると混乱をまねきそうｗ

とりあえず https://sakura-editor.osdn.jp/ は Developer 向けの情報ってことで
https://github.com/sakura-editor/sakura-editor.github.io/wiki のほうにだけリンク張っておきました。

**Comment by KENCHjp** [comment]
とりあえず、本件Closeします。
