### ISSUE TITLE
Google Analytics, Google Webmasters の組み込み

### ISSUE THREAD

**Issue by kobake** [sakura-editor/sakura-editor.github.io#14]
Google Analytics, Google Webmasters を組み込みたいと思っています。

仕事等ではひとつのGoogleアカウントを作ってメンバー間で共有とかやっちゃったりしてましたが、なんだか良くない気がします。OSSメンバー間でGoogleアカウントを共有というのもさらに良くない感じがします。

で、少し調べてみたのですが、認証タグを複数埋め込むことで複数人がウェブサイトの管理者として振る舞うことができそうです。

- [Googleウェブマスターツールを複数アカウントで使いたいんですが・・ - Google プロダクト フォーラム](https://productforums.google.com/forum/#!topic/webmaster-ja/dusSppgERIw)

試しに kobake 個人のアカウントで Google Analytics, Google Webmasters の設定を埋め込んでみようと思うのですが、どうでしょうか。

**Comment by m-tmatma** [comment]
試しにやってみたらいかがですか?

あと、このリポジトリは、私と @kobake さんしか watch していないみたいなので
明示的に mention しないと反応は得られないと思います。

**Comment by kobake** [comment]
アカウント運用のお作法とかあればアドバイス欲しいな～と思ってました。

> 試しにやってみたらいかがですか?

いろいろ並行作業してるのでちょっと後回しになりそうですが時間あるときにやってみます。

> あと、このリポジトリは、私と @kobake さんしか watch していないみたいなので
> 明示的に mention しないと反応は得られないと思います。

これは気づいてませんでした。たしかに Watcher 2人しかいないですね…。
@sakura-editor/sakura-developers たぶんこれでメンバーみんなにメンション飛ぶ（？）はず…？

**Comment by berryzplus** [comment]
メンション来ました〜。

完全に気付いておらんかったとです。

ドキュメンテーションに関する話題はこっちな雰囲気ですかね。

つまり。SALもこっち系…

**Comment by m-tmatma** [comment]
> ドキュメンテーションに関する話題はこっちな雰囲気ですかね。

ドキュメントというよりは Web site (https://sakura-editor.github.io/) に関する話題ですね。

**Comment by kobake** [comment]
そです。Web site オンリーですね。このリポジトリに対する変更内容は直接 https://sakura-editor.github.io/ に反映されます。

**Comment by berryzplus** [comment]
> ドキュメントというよりは Web site (https://sakura-editor.github.io/) に関する話題ですね

了解しました。

> このリポジトリに対する変更内容は直接 https://sakura-editor.github.io/ に反映されます。

ぼくの知らないハイテク技術が・・・ｗ
ブログとかwikiみたいなCMSのバックエンドがgitになってる感じをイメージしました。
サイトの一部として既にあがってるhtmlhelp(の元HTML)やdoxygen(の生成doc)の話をしていたわけですね。
既存であるものは引継ぐのがベターだと思っています。
そして、引き継ぐならメンテするのがベターだと思ってます。(これ、かなりキツそうですが。

とりあえず引き継いだとして、そういうのを取捨選択というか、
できるだけ需要あるものに力を注げるように Google Analyticsを活用するのは賛成です。
フォーラムの回答は「管理画面見たい人の分だけmetaタグ埋め込んでね」と読めます。
当座、 @kobake さんのアカウントでタグを埋め込んでみることに問題はないと思います。

**Comment by kobake** [comment]
Google Analytics と Google Webmasters の設定を完了しました。
サブページの表示のされ方が検索キーワードによって異なるのが謎ですが（後述の画像参照）。
とりあえず組み込みと設定は終わったので本 Issue はクローズします。

## 「サクラエディタ」での検索結果
<img width="539" alt="sakura-editor-jp" src="https://user-images.githubusercontent.com/2929454/41331966-ad36203c-6f16-11e8-88f5-2037423566ed.png">

## 「sakura editor」での検索結果
<img width="539" alt="sakura-editor-en" src="https://user-images.githubusercontent.com/2929454/41331967-afb2a506-6f16-11e8-944f-a7b1758ea539.png">

**Comment by kobake** [comment]
Google Analytics の集計が昨日の時点から始まりました。
OS 利用状況のグラフを以下 Wiki に貼っておきます。
https://github.com/sakura-editor/sakura-editor.github.io/wiki
