### ISSUE TITLE
htmlhelp を SourceForge から移行（まずは URL の策定）

### ISSUE THREAD

**Issue by kobake** [sakura-editor/sakura-editor.github.io#21]
http://sakura-editor.sourceforge.net/htmlhelp2/ を
https://sakura-editor.github.io/ 配下に移動しようと思います。

## URL の策定
そのまんま以前の URL 形式を踏襲するとしたら
`https://sakura-editor.github.io/htmlhelp2/` になりますが、
今現在の方針としては Unicode 版しかサポートしないので、
`2` は削って `https://sakura-editor.github.io/htmlhelp/` で良いかな、と思っています。

もしくは Web である時点で HTML であることは自明なので
`https://sakura-editor.github.io/help/` でも良いかもしれません。

ご意見あればください。

## 構築方法
理想としては sakura リポジトリ配下に help フォルダがあるので、それを参照する形（submodule や subtree 等）で取り込むのが良いと考えていますが、sakura の help フォルダが今後どうなるかまだ未確定なので、最初の段階としては単純にまるまるファイルコピーで構築する予定です。

## 今後の話
本 Issue の本題ではありませんが、今後の対応予定として考えていることを書き連ねておきます。

- sakura リポジトリからの参照方式の構築にする (submodule or subtree)
- macro や plugin の htmlhelp も Web に展開する（SourceForge 時代はこれは行われていなかった模様）
- hid2.cgi は廃止で良いと思う（単に数値から HLP0000XX.html のようなファイルにリダイレクトするだけのものなので）

**Comment by KENCHjp** [comment]
@kobake さんへ。
全体的に異論ないっす。

**Comment by m-tmatma** [comment]
リポジトリごとの GitHub Pages の機能を使えば、直接 sakura のリポジトリのデータを
web site に公開できます。

- https://blog.eiel.info/blog/2013/02/17/github-pages/
- https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

`https://sakura-editor.github.io/sakura/` という URL を許容できるならという話ですが。

**Comment by m-tmatma** [comment]
git submodule 等が使えるかの確認はしてますか？

**Comment by kobake** [comment]
まだしてないです。一旦避難してから諸々検証することを考えています。

**Comment by kobake** [comment]
そういえば subtree の検証はしていたことを思い出しました。
https://github.com/kobake/web-sandbox/tree/master/htmlhelp
https://kobake.github.io/web-sandbox/htmlhelp/HLP000001.html
何の加工もしてないので文字化けしてますが。

**Comment by KageShiron** [comment]
#22 
SourceForgeが不安定とのことなのでマージしました。
ヘルプファイルとの管理の兼ね合いなどを考えるためにこちらはまだOpenで良いかなと思います。

**Comment by kobake** [comment]
ありがとうございます！
あとでリダイレクト設定とかしておきます

**Comment by kobake** [comment]
> ヘルプファイルとの管理の兼ね合いなどを考えるためにこちらはまだOpenで良いかなと思います。

本 Issue の本題はあくまでもURLの決定（`/help/` で良いかどうか）であり、それについては解決した（異論はなく、元の提案通りの対応も行った）ため、クローズとさせてください。

この Issue で挙げた他の検討事項については #24, #25, #26 として別 Issue を立てました。
