### ISSUE TITLE
GitHub Ribbon をトップページの左上か右上に表示させる

### ISSUE THREAD

**Issue by kobake** [sakura-editor/sakura-editor.github.io#27]
こういうのを Web トップページの左上か右上に表示させようと思っています。

![forkme_left_red_aa0000](https://user-images.githubusercontent.com/2929454/41545215-ac6b7196-7355-11e8-8e89-08cbca0cd062.png)

ご意見あればください。

## 経緯
個人的な話ですが、ちょっと前にこういう↓会話の流れがありました。

「サクラエディタってオープンソースだったんだ」
「そうですよ。一応今のトップページの最下部にGitHubロゴ貼ってあります」
「うーん、下だと気づかないな～。最上部にリボン付けたら？」
「たしかに」

## 参考
- [GitHub Ribbons | The GitHub Blog](https://blog.github.com/2008-12-19-github-ribbons/)

**Comment by KageShiron** [comment]
オープンソースやGitHubを知らない方もいそうなので、ボランティアベースで開発をしていて、開発者や意見を探しています！みたいなことを表示すると興味を持ってくれそう

**Comment by m-tmatma** [comment]
> こういうのを Web トップページの左上か右上に表示させようと思っています。

いいと思います。
