### ISSUE TITLE
Slack バックアップ＆Slack廃止

### ISSUE THREAD

**Issue by kobake** [sakura-editor/sakura-editor.github.io#32]
Slack 廃止しますが、廃止前にバックアップをとって html として sakura-editor.github.io 上に設置予定です。

ただ、これは優先順位は低めで考えてます。（忘れないように Issue だけ登録しておく）

**Comment by kobake** [comment]
#34 にて Slack バックアップの保管完了しました。

@berryzplus せっかく作っていただいた 現Slack (sakura-editor.slack.com) ですが、今後は利用されなくなりますので削除処理を行っていただけますでしょうか。（たしか自分も管理権限持っていたはずですので、支障なければ僕のほうでやってもいいです）

**Comment by berryzplus** [comment]
任務完了 :smile:

**Comment by kobake** [comment]
確認遅くなりましたが消えてること確認できました～！ありがとうございます！
