### ISSUE TITLE
sakura リポジトリの HTML のヘルプ (help\sakura\_RESOURCE) を help に取り込む

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura-editor.github.io#47]
sakura リポジトリの HTML のヘルプ (help\sakura\res) を help に取り込む

sakura リポジトリの HTML のヘルプと web サイトのヘルプに相違があるので
最新版を取り込む。

ただし、sakura editor の 2.4.0.0 のリリースのタイミングまでmaster には入れないほうがよさそう。

例えば  develop 用のブランチを作ってそこに PR をマージして 2.4.0.0 が
リリースされたらmaster にマージするなどの運用が考えられる。

現状以下の違いがある。

## このリポジトリのデータ

1.

```
<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
```

2. HTML の文字コードが UTF-8
3. index.html が存在する
4. help/dsk_sakura.css の文字コードが UTF-8

## sakura リポジトリ

1.

```
<META http-equiv="Content-Type" content="text/html; charset=Shift_JIS">
```

2. HTML の文字コードが Shift-JIS
3. index.html が存在しない
4. help/dsk_sakura.css の文字コードが Shift-JIS

**Comment by berryzplus** [comment]
すぐPRする話ではないんですね :smile:

repository | version | charset | index | memo
-- | -- | -- | -- | --
[github.io/help](https://github.com/sakura-editor/sakura-editor.github.io/help) | ver 2.3.2.0 | UTF-8 | ある | 
[sakura/help/sakura](https://github.com/sakura-editor/sakura/help/sakura) | ver 2.4.0 (開発版) | Shift_JIS | ない | **追加ファイルあり**

* バージョン 「(開発版)」が取れる
* charset UTF-8 に変える。
* index.html スルー(現状維持)で。
* memo 追加ファイルはアピってもいい実績だと思ってます。

ぼくはドキュメントの内容は、本体の正常化が済んでからでもいいと思ってました。
差分眺めてみたんですけど、結構しょーもない誤変換してますね。
ver1系の内部コードがUTF-8になってて「げっ！」と思いました。
（`Shift_JIS`を一括置換したあと、雑なチェックで公開したんですね…。）

差分を見て見たら「サクッと通る」とは限らん気がしてきました。
こればっかりは、ブランチ切って先行でレビューするのがよいかもです。

ところで、helpのソースはUTF-8化しなくていいんでしたっけ？
HTML Help Workshopが対応してない？　・・・そんなまさか[！？](http://naka.wankuma.com/site/kaisetu/htmlhelp/00001.htm)

**Comment by m-tmatma** [comment]
> HTML Help Workshopが対応してない？　・・・そんなまさか[！？](http://naka.wankuma.com/site/kaisetu/htmlhelp/00001.htm)

そのページは過去に見てたので無理だと思ってましたが、
[本文に関してはいけるのかもしれない。](https://tohokuaiki.hateblo.jp/entry/20120813/1344863876)

**Comment by m-tmatma** [comment]
カレントディレクトリ以下の html の文字コード変換のスクリプトを作成

[convert.zip](https://github.com/sakura-editor/sakura-editor.github.io/files/2990478/convert.zip)

```
import codecs
import glob
import os
import re

def convert(input):
	output = input + ".tmp"
	lineno = 0
	with codecs.open(input, "r", "cp932") as fin:
		with codecs.open(output, "w", "utf-8") as fout:
			for line in fin:
				match = re.search(r'META', line)
				if match:
					line = re.sub('charset=Shift_JIS', 'charset=UTF-8', line)
				fout.write(line)
				lineno = lineno + 1
				
	os.unlink(input)
	os.rename(output, input)

def process_files(topdir):
	pattern = os.path.join(topdir, "*.html")
	files = glob.glob(pattern)
	
	for file in files:
		print (file)
		convert(file)

process_files(".")

```

**Comment by m-tmatma** [comment]
> そのページは過去に見てたので無理だと思ってましたが、
> [本文に関してはいけるのかもしれない。](https://tohokuaiki.hateblo.jp/entry/20120813/1344863876)

#807 で sakura 本体リポジトリの HTML HELP を UTF-8 に変換する PR を投げました。

**Comment by berryzplus** [comment]
> 本文に関してはいけるのかも

了解です。イケるはずのものとして、ローカルビルド確認と差分内容のレビューをしてみようと思います。

HTML Help workshop がaccess violationで落ちてるのは謎ですね。

appveyorのOS言語を日本語に変えてないのが影響してる？通る時と通らない時の違いは何だろう…

**Comment by m-tmatma** [comment]
> [sakura-editor/sakura#807](https://github.com/sakura-editor/sakura/pull/807) で sakura 本体リポジトリの HTML HELP を UTF-8 に変換する PR を投げました。

https://github.com/sakura-editor/sakura/pull/921 によって状況は改善する見込み。
https://github.com/sakura-editor/sakura/pull/921 マージ後に新しい PR で対応予定。

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/pull/937 のマージによって
準備が整った。

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/pull/939 を追加

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/pull/940 で https://github.com/sakura-editor/sakura/pull/937  と https://github.com/sakura-editor/sakura/pull/939 を revert

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/pull/940 を revert 後に対処予定

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/pull/1117
取り込み後に develop ブランチに取り込み予定

**Comment by m-tmatma** [comment]
> [sakura-editor/sakura#1117](https://github.com/sakura-editor/sakura/pull/1117) (← beta3 ブランチに対する PR)
> 取り込み後に develop ブランチに取り込み予定

Beta 3 を取り込み

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura-editor.github.io/pull/62
で master に適用済み
