### ISSUE TITLE
v2.4.0 リリースに合わせて修正する

### ISSUE THREAD

**Issue by takke** [sakura-editor/sakura-editor.github.io#48]
https://github.com/sakura-editor/management-forum/issues/66 より。

alpha版～正式リリースまでの間に Web も変更する必要があります。

何をどのように変更するのかこのIssueで整理したいです。

- トップ https://sakura-editor.github.io/ 
  - 「What's New」 の修正
- ダウンロード https://sakura-editor.github.io/download.html
  - 現状、「GitHub に移転準備中」と書かれていますし、全面的に変更が必要ですよね。

**Comment by m-tmatma** [comment]
v2.4.0 ブランチを作って、2.4.0 関連の修正をそのブランチにマージする。

リリースするときに、v2.4.0 ブランチを master にマージするというのを考えています。

**Comment by takke** [comment]
> v2.4.0 ブランチを作って、2.4.0 関連の修正をそのブランチにマージする。
> 
> リリースするときに、v2.4.0 ブランチを master にマージするというのを考えています。

なるほど。
@KENCHjp さんの[コメント](https://github.com/sakura-editor/management-forum/issues/66#issuecomment-477035354) もその意図のようなのでそういう流れだったんですね。了解です。

**Comment by KENCHjp** [comment]
>リリースするときに、v2.4.0 ブランチを master にマージするというのを考えています。

そっすね。修正をこつこつやっておいて、後で一気にマージってイメージでいます。

**Comment by m-tmatma** [comment]
あと、リリースブランチの保護設定も必要ですね。
これはサーバ側の設定ですが。

**Comment by takke** [comment]
> あと、リリースブランチの保護設定も必要ですね。
> これはサーバ側の設定ですが。

なるほど、ブランチを作るたびに(というかブランチ単位で)保護設定が必要だったんですね。
sakura 本体リポジトリに release/v2.4.0-alpha1 ブランチを作りましたけど、保護設定はしていないというか私に本体リポジトリの管理権限がないためか Settings タブが表示されてないです。こっちのリポジトリには Settings タブがあるので雰囲気は分かりました。

**Comment by m-tmatma** [comment]
[release/v2.4.0 のブランチ](https://github.com/sakura-editor/sakura-editor.github.io/tree/release/v2.4.0)を作って protect 設定しました。

<img width="636" alt="protect" src="https://user-images.githubusercontent.com/5567450/55269116-7837a300-52d3-11e9-8846-d88fbeb91f4d.png">

**Comment by m-tmatma** [comment]
毎回変えるのは面倒だと思うのでワイルドカードに変更しました。

<img width="591" alt="protect2" src="https://user-images.githubusercontent.com/5567450/55269265-af5a8400-52d4-11e9-9f5a-dfc6d563cad0.png">

**Comment by m-tmatma** [comment]
> [release/v2.4.0 のブランチ](https://github.com/sakura-editor/sakura-editor.github.io/tree/release/v2.4.0)を作って protect 設定しました。

`release/v2.4.0` ブランチは名前からしてリリース後に作成するブランチの気がするので
`develop-v2.4.0` というブランチを作って protect 設定しました。

**Comment by m-tmatma** [comment]
> `develop-v2.4.0` というブランチを作って protect 設定しました。

`develop` という名前にしました。

**Comment by KENCHjp** [comment]
Webはv2.4.0のブランチきりますかね。

ダウンロードページは、私案は、塩漬けして、リンク元で「旧ダウンロードページ」とする。
新ダウンロードページのリンクは、GitHubのReleaseページへのリンクのににしようかなと。
トップページは極力旧版の色を削除して、すっきりしたほうが後々メンテが楽かなと。
あ、あとヘルプページのリンク他も直さないとですね。
https://sakura-editor.github.io/help/

**Comment by KENCHjp** [comment]
>Webはv2.4.0のブランチきりますかね。

もう切ってありますね。
masterの変更を取り込んでからコツコツ修正していきますかね。

#47 ってどうすればいいっすか？ どなたか道筋ご教示を。(ヘルプの取り込み)
あとは #49 ぐらいかな。

**Comment by KENCHjp** [comment]
#24 #25 も絡んでますね。やれるところやって、テクニカルな部分はいったん先送りでリリースに集中しようかと。

**Comment by KENCHjp** [comment]
もっかい、最初からちゃんと流れを読むと（すいません）、一旦developブランチに修正を入れて、masterにマージって感じですかね？

**Comment by KENCHjp** [comment]
ブランチのdevelopをmasterへマージするときのオペレーションって、PR出すんすよね？
できたらGUI上で操作したいなと思っておりますが、
![キャプチャ](https://user-images.githubusercontent.com/39618965/72023576-81b85780-32b6-11ea-9a59-f82d5a5e3f10.PNG)
こんな感じで、Deveropブランチ表示後「New pull request」でマージできそうですがこれでいいっすかね？
大丈夫そうであればWikiのリリース手順修正しようかと思います。

本体側のブランチもちょっととっちらかっちゃいましたので、リリースに向けてalpha→beta→リリースでどういう風にブランチ作るかとか、betaの版重ねた時にどうしていくかとか手順を作っておいた方がよいっすね。

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura-editor.github.io/pull/62
で master にマージ済み
