### ISSUE TITLE
geocities終了に伴うリンク切れに対処

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura-editor.github.io#49]
詳細ダウンロードのとこの ANSI のリンクが切れているようです。

> 64bit版バイナリはこちら Unicode / ANSIです。(最新版ではありません。) 

対応が必要っぽいです。

**Comment by KENCHjp** [comment]
ANSIってどっかに公開されているんでしたっけ？
リンク削除かな。

**Comment by KENCHjp** [comment]
#48 にて対応予定。

**Comment by KENCHjp** [comment]
こちら閉じまーす。
