### ISSUE TITLE
htmlhelp の移行

### ISSUE THREAD

**Issue by kobake** [sakura-editor/sakura-editor.github.io#5]
http://sakura-editor.sourceforge.net/htmlhelp/ これも GitHub Pages 側に移す。

## TODO
- [x] ファイルコピー
- [x] リダイレクト設定
- [ ] 関連ドキュメントやアプリケーション等に埋め込まれているリンクの更新

**Comment by kobake** [comment]
## 関連
- htmlhelp を SourceForge から移行（まずは URL の策定） #21
- SourceForge の htmlhelp2 を GitHub Pages に移行 #22

**Comment by beru** [comment]
ソースコード中のオンラインヘルプのアドレス更新は下記のPRで対応済み
https://github.com/sakura-editor/sakura/pull/392

**Comment by m-tmatma** [comment]
google で `サクラエディタ` `ヘルプ` とかで検索すると
http://sakura-editor.sourceforge.net/htmlhelp/
が検索に引っかかります。

次期バージョン(ver 2.4.0.0) をリリース後に、
旧サイトの各ページから  https://sakura-editor.github.io/help/  あるいは対応するページに
リダイレクトする等、検索エンジンで github pages が引っかかるような対応を取りたいです。

**Comment by kobake** [comment]
現在は以下のようになっています。

- http://sakura-editor.sourceforge.net/htmlhelp/ … ver1 のヘルプ
- http://sakura-editor.sourceforge.net/htmlhelp2/ … ver2 のヘルプ: github.io 側にリダイレクトされる
- https://sakura-editor.github.io/help/ … ver2 のヘルプ

Google Webmasters の機能により ver2 のほうが優先して検索に引っかかるように操作をすることもできますが、何を正とすべきか自分は判断できないため、今のところは何もしていないです。

**Comment by KENCHjp** [comment]
これは、元がver1側が優先になっているので、一つはプログラムから遷移するヘルプが
github.ioになっていれば（仕組みとして)、Ok.かなと。
優先順位（SSO）はGoogle任せでいいかなと思いますがいかがでしょうか？
（みんなが、 https://sakura-editor.github.io/help/  こっち参照するようになればおのずとこっちがヒットするかと)

**Comment by KENCHjp** [comment]
@beru さん、 https://github.com/sakura-editor/sakura/pull/392 って、 https://github.com/sakura-editor/sakura-editor.github.io/issues/26 の対応済でしょうか？

**Comment by beru** [comment]
@KENCHjp さん、#26 については把握していませんでした。
見た感じ対応したことになっていそうですね。

**Comment by KENCHjp** [comment]
>見た感じ対応したことになっていそうですね。

いや決してそんなことにはなってないと思っております。
別PRで全然いいとおもうのですが、もしかして対応してるかとおもって。
GitHubではCGIつかえないので、専用関数をサクラで実装するか、
OSDNでCGI実装でもいいかなと。

らだ@koboke さん的にはcgi脱却がいいのかなとか。
とりあえず、現状の事実がわかればOk.です。

**Comment by beru** [comment]
https://github.com/sakura-editor/sakura/pull/392/files

だと対応した事になっていないですか？
もし何か修正が必要であれば PR を作成されるのが良いと思います。

**Comment by KENCHjp** [comment]
>だと対応した事になっていないですか？

いえ、とりあえずIssueは行きてますし、このやり取りで現状の事実が明示だとおもうので、
必要に応じてPRをだれかが投げればいいんではないかとおもいます。

**Comment by KENCHjp** [comment]
>だと対応した事になっていないですか？


ごめんなさい。
改めてソース見ましたが、対応できてる実装のようですね。
失礼しました。

もうちょっと見て、閉じれそうなら諸々とじます。
失礼しました！

**Comment by beru** [comment]
いえいえ、問題無かったようで安心しました。

あと、他のサイトにある関連ドキュメンテーションは結構多いのでそれを github にも載せるのは手間がかかりそうですね。

**Comment by KENCHjp** [comment]
@beru さん動作確認もしました。問題ないです。
日本語取り違えしまして何度もやり取りしてすいませんでした。

**Comment by beru** [comment]
@KENCHjp ちょっと別件になるのですが、このリポジトリ（`sakura-editor.github.io`）のパーミッション設定をお願いしてもいいでしょうか？ Settings タブをクリックすると Danger Zone の Delete this repository ボタンが表示されています。Sakura Editor organization の Owner のみにそれは限定した方が良いと思います。Member は数が多いので誤操作が心配です。

**Comment by beru** [comment]
`googletest` と `sandbox` リポジトリも同様ですね。

まぁここらへんはポリシーに関わる事だと思いますが、Member が Delete this repository 操作を行う必要性があるかというと多分無いのではないかと思います。

設定や管理などで Owner の方々の手間が少し増えてしまうと思いますが、まぁそういう Role ですのでお手数ですがご検討ください。

**Comment by KENCHjp** [comment]
>関連ドキュメントやアプリケーション等に埋め込まれているリンクの更新

こちらは、リリースしてから着手たほうがいいかなと。
リリース出来ないことには意味が無いし着手もまずいかなと。

**Comment by beru** [comment]
>> 関連ドキュメントやアプリケーション等に埋め込まれているリンクの更新

> こちらは、リリースしてから着手たほうがいいかなと。
リリース出来ないことには着手する資格が無い気がしています。

ん、これって関連ドキュメントの更新の事でしょうか？
アプリケーション等に埋め込まれているリンクの更新は、もう対処済みでリリースする前に直す必要があるという認識ですが…。

そもそも関連ドキュメントとは何ぞや、といったところですね。
それが明確になっていればどう対処するかの道筋をつけやすいかと思います。

**Comment by KENCHjp** [comment]
>アプリケーション等に埋め込まれているリンクの更新は、もう対処済みでリリースする前に直す必要があるという認識ですが…。

はい、こちらは、 https://github.com/sakura-editor/sakura/pull/383 で修正済かなと認識しています。

カンバン（Project）側にToDoで書きましたが、
ひとまず、sakura-editor/sakura-editor.github.io の中を「sourceforge.net」で検索した結果に対してと思っております。

**Comment by KENCHjp** [comment]
>これに関してですが、リリース前に直してしまった方が良いと思います。v 2.4.0 をリリースすると訪れる人が増えると思うのでその時に見るページ内のリンクが古いと良くないかなと。

それはそう思いますが、先にホームページ直したあと延々とReleaseしないとそれはそれでよくないと思うので、
Release確定してから、直前（かほぼ同時）の認識でいます。

**Comment by KENCHjp** [comment]
こっちのチームでReleaseしてないうちはまだ、前のパッケージがサクラエディタ的には正かと思うので。

**Comment by beru** [comment]
別 branch で修正作業を行えば良いのではないかと思います。

**Comment by KENCHjp** [comment]
>別 branch で修正作業を行えば良いのではないかと思います。

なる、準備しておいて、マージですね。

**Comment by KENCHjp** [comment]
本件も閉じますね。移行自体はできていると思うので。
